#!/bin/sh

tce-load -i bash.tcz
tce-load -i socat.tcz
tce-load -i util-linux.tcz

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_WANTNONEDRIVERWARNING=false
export MINIKUBE_HOME=${MINIKUBE_HOME:-$HOME}
export CHANGE_MINIKUBE_NONE_USER=true
sudo -E minikube start --vm-driver=none \
	--apiserver-ips=127.0.0.1 \
	--kubernetes-version=`cat ~/.kube/version`
