#!/bin/sh

PARTNAME=sda1

ln -s /mnt/$PARTNAME/home/docker/kubectl /home/docker/kubectl
ln -s /mnt/$PARTNAME/home/docker/.kube /home/docker/.kube
ln -s /mnt/$PARTNAME/home/docker/minikube /home/docker/minikube
ln -s /mnt/$PARTNAME/home/docker/.minikube /home/docker/.minikube

ln -s /mnt/$PARTNAME/home/docker/kubectl /usr/local/bin/kubectl
ln -s /mnt/$PARTNAME/var/lib/kubelet /var/lib/kubelet
ln -s /mnt/$PARTNAME/home/docker/minikube /usr/local/bin/minikube
ln -s /mnt/$PARTNAME/var/lib/localkube /var/lib/localkube

test -d /data || ln -s /mnt/$PARTNAME/data /data

test -L /tmp/hostpath_pv && rm /tmp/hostpath_pv
mkdir /tmp/hostpath_pv
mount --bind /mnt/$PARTNAME/hostpath_pv /tmp/hostpath_pv
test -L /tmp/hostpath-provisioner && rm /tmp/hostpath-provisioner
mkdir /tmp/hostpath-provisioner
mount --bind /mnt/$PARTNAME/hostpath-provisioner /tmp/hostpath-provisioner

cp /mnt/$PARTNAME/tce/optional/* /tmp/tce/optional/

# https://github.com/kubernetes/kubernetes/pull/61126
mount --make-rshared /
/etc/init.d/docker restart
